# Generated by Django 3.2 on 2021-05-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('prof_pic', models.ImageField(default='no_pic.png', upload_to='drivers')),
                ('eq_type', models.CharField(max_length=200)),
            ],
        ),
    ]
